#!/usr/bin/env bash
# displays a list of currently running processes.
# show all processes, for all users, including those
# which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

echo "PID   USER     TTY      STAT   START   TIME COMMAND"
ps -e -o pid,user,tty,stat,start,time,comm --forest
