#!/usr/bin/env bash
# displays a list of currently running processes.
# show all processes, for all users, including those
# which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

echo "Currently Running Processes (All Users)"
echo "-------------------------------------"

tree_output=$(ps -e --forest -o pid,user,tty,%cpu,%mem,cmd)

echo "$tree_output"
