#!/usr/bin/env bash
# displays the PID, along with the process name, of
# processes whose name contain the word bash

for pid in /proc/[0-9]*; do
  if [[ -d "$pid" ]]; then
    comm_file="$pid/comm"
    if [[ -f "$comm_file" ]]; then
      process_name=$(cat "$comm_file")
      if [[ "$process_name" == *"bash"* ]]; then
        echo "PID: $(basename "$pid") - Process: $process_name"
      fi
    fi
  fi
done
