#!/usr/bin/env bash
# stopped our 4-to_infinity_and_beyond process
# using ctrl+c in the previous task

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [[ -n "$pid" ]]; then
	kill "$pid"
	echo "Process 4-to_infinity_and_beyond (PID: $pid) has been terminated."
else
	echo "No 4-to_infinity_and_beyond process found."
fi
