#!/usr/bin/env bash
# stopped our 4-to_infinity_and_beyond process
# using ctrl+c in the previous task

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [[ -n "$pid" ]]; then
  # Kill the process.
  kill "$pid"
  echo "Process with PID $pid killed."
else
  echo "Process not found."
fi
