#!/usr/bin/env bash
# stopped our 4-to_infinity_and_beyond process
# using ctrl+c in the previous task

pid=$(pgrep -f "echo \"To infinity and beyond\"")

# Check if the process was found
if [[ -n "$pid" ]]; then
    echo "Stopping process with PID: $pid"
    kill "$pid"
else
    echo "Process not found."
fi
