#!/usr/bin/env bash
# kill "7-highlander

pid=$(pgrep -f "7-highlander")

# Check if the process was found
if [[ -n "$pid" ]]; then
    echo "Stopping process 7-highlander with PID: $pid"
    kill "$pid"
else
    echo "Process 7-highlander not found."
fi
