#!/usr/bin/env bash
# kill "7-highlander

pid=$(pgrep -f "7-highlander")

if [[ -n "$pid" ]]; then
  # Kill the process.
  kill "$pid"
  echo "Process with PID $pid killed."
else
  echo "Process not found."
fi
