#!/usr/bin/env bash
# kill "7-highlander

pid=$(pgrep -f "7-highlander")

# Check if the process was found
if [[ -n "$pid" ]]; then
  # Send SIGTERM signal to the process
  kill -SIGTERM "$pid"
  echo "Sent SIGTERM to 7-highlander (PID: $pid)."
else
  echo "No 7-highlander process found."
fi
