#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
# Only displays the username, user id, and user home directory path.

while IFS=: read -r username _ userid _ _ homedir _; do

	echo "The user $username has user id $userid and home directory at $homedir"
done < /etc/passwd
