#!/usr/bin/env bash
# Parses Apache log files in list format.
#   Groups visitors by IP and HTTP status code.
#   Displays the number of occurrences, IP, and HTTP status
#+  code of each log, in sorted order.

LOG_FILE="access.log"

awk '{ ip[$1 " " $9]++ } END { for (key in ip) print ip[key], key }' "$LOG_FILE" | sort -nr
