#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# for the 9th iteration, displays Best School and then Hi

i=0
while [ $i -le 10 ]; do
	if [ $i -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
