#!/usr/bin/env bash
# This script displays the content of the current directory in list format, only the part of the name after the first dash is displayed

for item in *; do

	if [[ "$item" != .* ]]; then

		name_after_dash="${item#*-}"

		echo "$name_after_dash"
	fi
done
